; Test link ESP32 -> UNO (solo nRF24)
[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_speed = 921600
lib_deps = tmrh20/RF24@^1.4.1
build_flags = -DCORE_DEBUG_LEVEL=3
